### ISSUE TITLE
Survey modal - attribute value incorrect

### ISSUE THREAD

**Issue by JayOram** [braze-inc/in-app-message-templates#12]
In the Survey modal with checkboxes - the attribute value submitted is only ever the first input.

**Comment by davidbielik** [comment]
Hi @JayOram that's expected behavior if you re-use the same attribute-name for all choices as it loops through the choices and sets a custom attribute for each key/value.

You could either customize the javascript to change the logic to set an array, or, we've added a new out-of-the-box survey type your team can find here: https://www.braze.com/docs/user_guide/message_building_by_channel/in-app_messages/templates/simple_survey/

Let me know if that makes sense!

**Comment by JayOram** [comment]
Thanks for the explanation - I will take a look at the new out of the box solution as well!
